services:
  vllm:
    image: vllm/vllm-openai:v0.6.4
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              device_ids: [ "7" ]
    ports:
      - "9006:8000"
    env_file:
      - .env
    ipc: host
    command: --model microsoft/Phi-3.5-mini-instruct --max_model_len 32000
