[project]
name = "templates-gpus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "openai>=1.57.4",
    "vllm>=0.6.4.post1",
]
